# Generated by Django 2.1 on 2019-01-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('degree', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('Dealing_people', models.CharField(max_length=15)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
