# Generated by Django 2.1 on 2019-01-24 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0002_bug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bug',
        ),
    ]
