# Generated by Django 2.1 on 2019-01-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0006_bug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bug',
        ),
    ]
